# Generated by Django 3.0.1 on 2020-02-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='files',
        ),
    ]
